### ISSUE TITLE
too wide a revert ?

### ISSUE THREAD

**Issue by prahal** [patriziobruno/grubreboot-gnome-shell-extension#11]
commit 562679d6fb59f2ca653cc361af3e8b3d66539423
tells it is a french translation revert. But it does revert more than the translation:
- legacy /boot/grub2/grub.cfg support
- /boot/efi protected support
Should this code get back in ? (I am not on fedora so cannot test those)

**Comment by patriziobruno** [comment]
I reverted the commit because of changesets related to efi in a pull request that should have contained only a french translation. The /boot/efi protected code added some usability issues and had already been removed by the author.
