### ISSUE TITLE
This extension selects system permanently

### ISSUE THREAD

**Issue by pmaselkowski** [patriziobruno/grubreboot-gnome-shell-extension#16]
Hi!

I've installed this extension having set "Boot previous entry" in grub customizer. When I've chosen "Restart to.." option and used Windows &reg;, it has set my default OS to Windows &reg; and each subsequent reboot is trying to start Windows &reg;.

> &reg; Sign for Windows &reg; lawyers make happy that they are assured that they trademark is registered;)

**Comment by patriziobruno** [comment]
Hi @pmaselkowski,
That depends on your grub configuration, the extension is nothing else than a GUI for the utility [grub-reboot](https://www.commandlinux.com/man-page/man8/grub-reboot.8.html). You may want to set your grub configuration properly before using the extension, [this stackexchange](https://unix.stackexchange.com/questions/43196/how-can-i-tell-grub-i-want-to-reboot-into-windows-before-i-reboot) might prove useful. The standard Ubuntu configuration should work just fine though.

**Comment by patriziobruno** [comment]
#bdab565
